#! /usr/bin/env python3
import json
import tweepy
from tweepy.parsers import JSONParser
import datetime

def _twit_auth():
    consumer_key = 'Your consumer key'
    consumer_secret = 'Your consumer secret'
    access_key = 'Your access key'
    access_secret = 'your access secret'
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_key, access_secret)
    api = tweepy.API(auth, parser=JSONParser())

    return api

def _send_url(status_id, user):
    auth = _twit_auth()
    post = auth.get_status(status_id)['text'].replace(' (1/2)', '').replace(' (2/2)', '')
    post_log = open('TIL.log', 'rU')
    post_log_list = []

    for line in post_log:
        if line[0] == '{':
            post_log_list.append(json.loads(line))

    for data in post_log_list:
        if post in data['post']:
            text = '@%s %s' % (user, data['url'])
            _twit_auth().update_status(text, status_id)

def main():

    reply_dict = {'data':[]}

    try:
        log_check = open('reply.log', 'rU')
        for line in log_check:
            if line[0] == '{':
                reply_dict['data'].append(json.loads(line))
        log_check.close()
    except FileNotFoundError:
        pass

    auth = _twit_auth()

    twt = auth.search('to:TIL_Bot_')

    reply_log = open('reply.log', 'a')
    reply_log.write('\n' + str(datetime.datetime.now()) + '\n\n')

    for tweet in twt['statuses']:
        if any(d['id'] == tweet['in_reply_to_status_id'] for d in reply_dict['data']) == False:
            _send_url(tweet['in_reply_to_status_id'], tweet['user']['screen_name'])
            tweet_data = {'id':tweet['in_reply_to_status_id'], 'user':tweet['user']['screen_name'], 'text':tweet['text']}
            reply_log.write(json.dumps(tweet_data) + '\n')


if __name__ == '__main__':
    main()

